In [1]:
import numpy as np

In [16]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [5]:
print(x[1,2])

8


In [4]:
a=[1,2]
print(x[a])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [6]:
print(x[::3,::2])

[[ 1  3  5]
 [16 18 20]]


In [7]:
print(x[1::3,::2])

[[ 6  8 10]
 [21 23 25]]


In [8]:
# 多种整型数组索引栗子
y=np.array(range(10))
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
b = np.array([[1,2],[3,4]])

In [16]:
print(x[b])

[[[ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]]]


In [15]:
print(y[b])

[[1 2]
 [3 4]]


In [ ]:
可以把b看成两个“下标”，x[b]和y[b]分别是含有两个元素的“一维数组”，但是他们的元素是两个一维数组。

In [8]:
print(np.take(x, a, axis=0))

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
print(np.take(x, a, axis=1))

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]]


In [6]:
print(np.take(x, b, axis=0))

[[[ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]]]


In [7]:
print(np.take(x, b, axis=1))

[[[ 2  3]
  [ 4  5]]

 [[ 7  8]
  [ 9 10]]

 [[12 13]
  [14 15]]

 [[17 18]
  [19 20]]

 [[22 23]
  [24 25]]]


In [10]:
# 布尔索引
x = np.array([1, 2, 3, 4, 5, 6, 7, 8]) 
y = x > 5 
print(y)

[False False False False False  True  True  True]


In [11]:
print(x[x > 5])

[6 7 8]


In [12]:
print(x[y])

[6 7 8]


In [19]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [20]:
# numpy.apply_along_axis()
z1 = np.apply_along_axis(np.sum, 0, x) 
print(z1)  

[55 60 65 70 75]


运算过程：对内部五个一维数组的第一个元素求和得到结果的第一个值，即按行遍历，每行先取第一个，求和得到结果的第一个值，1+6+11+16+21=55，再取每行的第二个数，求和得到结果的第二个值,2+7+12+17+22=60，以此类推得到剩下四个结果。

In [21]:
z2 = np.apply_along_axis(np.sum, 1, x) 
print(z2) 

[ 15  40  65  90 115]


运算过程：对内部五个一维数组分别求和得到结果，即按列遍历，每列先取第一个，求和得到结果的第一个值，然后再取每列第二个，得到结果的第二个值，以此类推。

还可以写其他较复杂函数进行操作。